import './globals.css';
import Navbar from '@/components/Navbar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='antialiased'>
        <div className='flex flex-col h-screen'>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
